# Generated by Django 3.0.7 on 2020-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200825_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_menu',
            field=models.BooleanField(default=False, verbose_name='Categoria en el menu'),
        ),
    ]
