# Generated by Django 3.0.7 on 2020-09-21 13:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200916_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido de la Noticia'),
        ),
    ]
