# Generated by Django 3.0.7 on 2021-01-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200921_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_user_save',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
