# Generated by Django 3.0.7 on 2021-03-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_date_user_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='¿Es popular?'),
        ),
    ]
